version: 2
updates:
    # Enable version updates for Docker
    - package-ecosystem: "docker"
      directory: "./docker"
      schedule:
          interval: "daily"

    # Enable version updates for GitHub Actions
    - package-ecosystem: "github-actions"
      directory: "./.github/workflows"
      schedule:
          interval: "daily"
    # Enable version updates for .NET
    - package-ecosystem: "nuget"
      directory: "./src"
      schedule:
          interval: "daily"
