// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Flights.Api.AcceptanceTests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class BookSeatForFlightFeature : object, Xunit.IClassFixture<BookSeatForFlightFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "BookSeatForFlight.feature"
#line hidden
        
        public BookSeatForFlightFeature(BookSeatForFlightFeature.FixtureData fixtureData, Flights_Api_AcceptanceTests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Book seat for flight", "    As a user\r\n    I want to book a seat for a flight\r\n    So that the seat is re" +
                    "served for the passenger", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Book a seat for a flight")]
        [Xunit.TraitAttribute("FeatureTitle", "Book seat for flight")]
        [Xunit.TraitAttribute("Description", "Book a seat for a flight")]
        public void BookASeatForAFlight()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Book a seat for a flight", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 6
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                            "FlightNumber",
                            "DepartureAirportIataCode",
                            "DepartureAirportTimeZone",
                            "DestinationAirportIataCode",
                            "DestinationAirportTimeZone",
                            "DepartureTime",
                            "ArrivalTime",
                            "EconomyPrice",
                            "BusinessPrice"});
                table1.AddRow(new string[] {
                            "EA123",
                            "YVR",
                            "America/Vancouver",
                            "CDG",
                            "Europe/Paris",
                            "2026-01-01T10:00:00",
                            "2026-01-02T05:00:00",
                            "1200.00",
                            "4500.00"});
#line 7
        testRunner.Given("the following flights exist:", ((string)(null)), table1, "Given ");
#line hidden
#line 10
        testRunner.When("seat 1A in Business class on flight EA123 is booked for passenger John Doe with e" +
                        "mail address john.doe@aol.com", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 11
        testRunner.Then("seat 1A in Business class on flight EA123 is booked for passenger John Doe with e" +
                        "mail address john.doe@aol.com at a price of 4500.00", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                BookSeatForFlightFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                BookSeatForFlightFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
