// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Flights.Api.AcceptanceTests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class GetSeatsForAFlightFeature : object, Xunit.IClassFixture<GetSeatsForAFlightFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "GetSeatsForFlight.feature"
#line hidden
        
        public GetSeatsForAFlightFeature(GetSeatsForAFlightFeature.FixtureData fixtureData, Flights_Api_AcceptanceTests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Get Seats for a Flight", "    As a customer\r\n    I want to retrieve the seats for a flight\r\n    So that I c" +
                    "an select a seat when booking", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Get seats for a flight without a seat type filter")]
        [Xunit.TraitAttribute("FeatureTitle", "Get Seats for a Flight")]
        [Xunit.TraitAttribute("Description", "Get seats for a flight without a seat type filter")]
        public void GetSeatsForAFlightWithoutASeatTypeFilter()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Get seats for a flight without a seat type filter", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 6
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                            "FlightNumber",
                            "DepartureAirportIataCode",
                            "DepartureAirportTimeZone",
                            "DestinationAirportIataCode",
                            "DestinationAirportTimeZone",
                            "DepartureTime",
                            "ArrivalTime",
                            "EconomyPrice",
                            "BusinessPrice"});
                table2.AddRow(new string[] {
                            "EA123",
                            "YVR",
                            "America/Vancouver",
                            "CDG",
                            "Europe/Paris",
                            "2026-01-01T10:00:00",
                            "2026-01-02T05:00:00",
                            "1200.00",
                            "4500.00"});
#line 7
        testRunner.Given("the following flights exist:", ((string)(null)), table2, "Given ");
#line hidden
#line 10
        testRunner.When("I get the seats for flight EA123", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                            "SeatType",
                            "Count",
                            "Price",
                            "Available"});
                table3.AddRow(new string[] {
                            "Economy",
                            "301",
                            "1200",
                            "301"});
                table3.AddRow(new string[] {
                            "Business",
                            "36",
                            "4500",
                            "36"});
#line 11
        testRunner.Then("the following seat groups are returned:", ((string)(null)), table3, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Get seats for a flight filtered by seat type")]
        [Xunit.TraitAttribute("FeatureTitle", "Get Seats for a Flight")]
        [Xunit.TraitAttribute("Description", "Get seats for a flight filtered by seat type")]
        public void GetSeatsForAFlightFilteredBySeatType()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Get seats for a flight filtered by seat type", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 16
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                            "FlightNumber",
                            "DepartureAirportIataCode",
                            "DepartureAirportTimeZone",
                            "DestinationAirportIataCode",
                            "DestinationAirportTimeZone",
                            "DepartureTime",
                            "ArrivalTime",
                            "EconomyPrice",
                            "BusinessPrice"});
                table4.AddRow(new string[] {
                            "EA123",
                            "YVR",
                            "America/Vancouver",
                            "CDG",
                            "Europe/Paris",
                            "2026-01-01T10:00:00",
                            "2026-01-02T05:00:00",
                            "1200.00",
                            "4500.00"});
#line 17
        testRunner.Given("the following flights exist:", ((string)(null)), table4, "Given ");
#line hidden
#line 20
        testRunner.When("I get the economy seats for flight EA123", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                            "SeatType",
                            "Count",
                            "Price",
                            "Available"});
                table5.AddRow(new string[] {
                            "Economy",
                            "301",
                            "1200",
                            "301"});
#line 21
        testRunner.Then("the following seat groups are returned:", ((string)(null)), table5, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                GetSeatsForAFlightFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                GetSeatsForAFlightFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
