// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Flights.Api.AcceptanceTests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class SearchForFlightsByRouteAndDateFeature : object, Xunit.IClassFixture<SearchForFlightsByRouteAndDateFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "SearchForFlightsByRouteAndDate.feature"
#line hidden
        
        public SearchForFlightsByRouteAndDateFeature(SearchForFlightsByRouteAndDateFeature.FixtureData fixtureData, Flights_Api_AcceptanceTests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Search for flights by route and date", "    As a customer\r\n    I want to search for flights by route and date\r\n    So tha" +
                    "t I can evaluate the options available to me", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Search for flights by route and date with valid results")]
        [Xunit.TraitAttribute("FeatureTitle", "Search for flights by route and date")]
        [Xunit.TraitAttribute("Description", "Search for flights by route and date with valid results")]
        public void SearchForFlightsByRouteAndDateWithValidResults()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Search for flights by route and date with valid results", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 6
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                            "FlightNumber",
                            "DepartureAirportIataCode",
                            "DepartureAirportTimeZone",
                            "DestinationAirportIataCode",
                            "DestinationAirportTimeZone",
                            "DepartureTime",
                            "ArrivalTime",
                            "EconomyPrice",
                            "BusinessPrice",
                            "AvailableEconomySeats",
                            "AvailableBusinessSeats"});
                table1.AddRow(new string[] {
                            "EA123",
                            "YVR",
                            "America/Vancouver",
                            "CDG",
                            "Europe/Paris",
                            "2025-01-01T10:00:00",
                            "2025-01-02T05:00:00",
                            "1200.00",
                            "4500.00",
                            "50",
                            "10"});
                table1.AddRow(new string[] {
                            "EA124",
                            "YVR",
                            "America/Vancouver",
                            "CDG",
                            "Europe/Paris",
                            "2025-01-01T14:00:00",
                            "2025-01-02T09:00:00",
                            "1200.00",
                            "4500.00",
                            "50",
                            "10"});
                table1.AddRow(new string[] {
                            "EA125",
                            "YVR",
                            "America/Vancouver",
                            "LHR",
                            "Europe/London",
                            "2025-01-01T09:00:00",
                            "2025-01-02T04:00:00",
                            "1000.00",
                            "4000.00",
                            "60",
                            "15"});
#line 7
        testRunner.Given("the following flights exist:", ((string)(null)), table1, "Given ");
#line hidden
#line 12
        testRunner.When("I search for flights from YVR to CDG on 2025-01-01", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                            "FlightNumber",
                            "DepartureAirportIataCode",
                            "DepartureAirportTimeZone",
                            "DestinationAirportIataCode",
                            "DestinationAirportTimeZone",
                            "DepartureTime",
                            "ArrivalTime",
                            "EconomyPrice",
                            "BusinessPrice",
                            "AvailableEconomySeats",
                            "AvailableBusinessSeats"});
                table2.AddRow(new string[] {
                            "EA123",
                            "YVR",
                            "America/Vancouver",
                            "CDG",
                            "Europe/Paris",
                            "2025-01-01T10:00:00",
                            "2025-01-02T05:00:00",
                            "1200.00",
                            "4500.00",
                            "50",
                            "10"});
                table2.AddRow(new string[] {
                            "EA124",
                            "YVR",
                            "America/Vancouver",
                            "CDG",
                            "Europe/Paris",
                            "2025-01-01T14:00:00",
                            "2025-01-02T09:00:00",
                            "1200.00",
                            "4500.00",
                            "50",
                            "10"});
#line 13
        testRunner.Then("the following flights are returned:", ((string)(null)), table2, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="No flights available for the given route and date")]
        [Xunit.TraitAttribute("FeatureTitle", "Search for flights by route and date")]
        [Xunit.TraitAttribute("Description", "No flights available for the given route and date")]
        public void NoFlightsAvailableForTheGivenRouteAndDate()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("No flights available for the given route and date", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 18
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                            "FlightNumber",
                            "DepartureAirportIataCode",
                            "DepartureAirportTimeZone",
                            "DestinationAirportIataCode",
                            "DestinationAirportTimeZone",
                            "DepartureTime",
                            "ArrivalTime",
                            "EconomyPrice",
                            "BusinessPrice",
                            "AvailableEconomySeats",
                            "AvailableBusinessSeats"});
                table3.AddRow(new string[] {
                            "EA123",
                            "YVR",
                            "America/Vancouver",
                            "CDG",
                            "Europe/Paris",
                            "2025-01-02T10:00:00",
                            "2025-01-03T05:00:00",
                            "1200.00",
                            "4500.00",
                            "50",
                            "10"});
#line 19
        testRunner.Given("the following flights exist:", ((string)(null)), table3, "Given ");
#line hidden
#line 22
        testRunner.When("I search for flights from YVR to CDG on 2025-01-01", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 23
        testRunner.Then("no flights are returned", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Search for flights with no matching route")]
        [Xunit.TraitAttribute("FeatureTitle", "Search for flights by route and date")]
        [Xunit.TraitAttribute("Description", "Search for flights with no matching route")]
        public void SearchForFlightsWithNoMatchingRoute()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Search for flights with no matching route", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 25
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                            "FlightNumber",
                            "DepartureAirportIataCode",
                            "DepartureAirportTimeZone",
                            "DestinationAirportIataCode",
                            "DestinationAirportTimeZone",
                            "DepartureTime",
                            "ArrivalTime",
                            "EconomyPrice",
                            "BusinessPrice",
                            "AvailableEconomySeats",
                            "AvailableBusinessSeats"});
                table4.AddRow(new string[] {
                            "EA123",
                            "YVR",
                            "America/Vancouver",
                            "LHR",
                            "Europe/London",
                            "2025-01-01T10:00:00",
                            "2025-01-02T05:00:00",
                            "1000.00",
                            "4000.00",
                            "60",
                            "15"});
#line 26
        testRunner.Given("the following flights exist:", ((string)(null)), table4, "Given ");
#line hidden
#line 29
        testRunner.When("I search for flights from YVR to CDG on 2025-01-01", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 30
        testRunner.Then("no flights are returned", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Search with invalid date format")]
        [Xunit.TraitAttribute("FeatureTitle", "Search for flights by route and date")]
        [Xunit.TraitAttribute("Description", "Search with invalid date format")]
        public void SearchWithInvalidDateFormat()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Search with invalid date format", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 32
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 33
        testRunner.When("I search for flights from YVR to CDG on 2025-01-100", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 34
        testRunner.Then("an error message is returned which states that the date format is invalid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Search with lowercase airport codes")]
        [Xunit.TraitAttribute("FeatureTitle", "Search for flights by route and date")]
        [Xunit.TraitAttribute("Description", "Search with lowercase airport codes")]
        public void SearchWithLowercaseAirportCodes()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Search with lowercase airport codes", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 36
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                            "FlightNumber",
                            "DepartureAirportIataCode",
                            "DepartureAirportTimeZone",
                            "DestinationAirportIataCode",
                            "DestinationAirportTimeZone",
                            "DepartureTime",
                            "ArrivalTime",
                            "EconomyPrice",
                            "BusinessPrice",
                            "AvailableEconomySeats",
                            "AvailableBusinessSeats"});
                table5.AddRow(new string[] {
                            "EA123",
                            "YVR",
                            "America/Vancouver",
                            "CDG",
                            "Europe/Paris",
                            "2025-01-01T10:00:00",
                            "2025-01-02T05:00:00",
                            "1200.00",
                            "4500.00",
                            "50",
                            "10"});
#line 37
        testRunner.Given("the following flights exist:", ((string)(null)), table5, "Given ");
#line hidden
#line 40
        testRunner.When("I search for flights from yvr to cdg on 2025-01-01", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                            "FlightNumber",
                            "DepartureAirportIataCode",
                            "DepartureAirportTimeZone",
                            "DestinationAirportIataCode",
                            "DestinationAirportTimeZone",
                            "DepartureTime",
                            "ArrivalTime",
                            "EconomyPrice",
                            "BusinessPrice",
                            "AvailableEconomySeats",
                            "AvailableBusinessSeats"});
                table6.AddRow(new string[] {
                            "EA123",
                            "YVR",
                            "America/Vancouver",
                            "CDG",
                            "Europe/Paris",
                            "2025-01-01T10:00:00",
                            "2025-01-02T05:00:00",
                            "1200.00",
                            "4500.00",
                            "50",
                            "10"});
#line 41
        testRunner.Then("the following flights are returned:", ((string)(null)), table6, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Search with mixed case airport codes")]
        [Xunit.TraitAttribute("FeatureTitle", "Search for flights by route and date")]
        [Xunit.TraitAttribute("Description", "Search with mixed case airport codes")]
        public void SearchWithMixedCaseAirportCodes()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Search with mixed case airport codes", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 45
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                            "FlightNumber",
                            "DepartureAirportIataCode",
                            "DepartureAirportTimeZone",
                            "DestinationAirportIataCode",
                            "DestinationAirportTimeZone",
                            "DepartureTime",
                            "ArrivalTime",
                            "EconomyPrice",
                            "BusinessPrice",
                            "AvailableEconomySeats",
                            "AvailableBusinessSeats"});
                table7.AddRow(new string[] {
                            "EA123",
                            "YVR",
                            "America/Vancouver",
                            "CDG",
                            "Europe/Paris",
                            "2025-01-01T10:00:00",
                            "2025-01-02T05:00:00",
                            "1200.00",
                            "4500.00",
                            "50",
                            "10"});
#line 46
        testRunner.Given("the following flights exist:", ((string)(null)), table7, "Given ");
#line hidden
#line 49
        testRunner.When("I search for flights from YvR to CdG on 2025-01-01", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                            "FlightNumber",
                            "DepartureAirportIataCode",
                            "DepartureAirportTimeZone",
                            "DestinationAirportIataCode",
                            "DestinationAirportTimeZone",
                            "DepartureTime",
                            "ArrivalTime",
                            "EconomyPrice",
                            "BusinessPrice",
                            "AvailableEconomySeats",
                            "AvailableBusinessSeats"});
                table8.AddRow(new string[] {
                            "EA123",
                            "YVR",
                            "America/Vancouver",
                            "CDG",
                            "Europe/Paris",
                            "2025-01-01T10:00:00",
                            "2025-01-02T05:00:00",
                            "1200.00",
                            "4500.00",
                            "50",
                            "10"});
#line 50
        testRunner.Then("the following flights are returned:", ((string)(null)), table8, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Search with missing departure airport code")]
        [Xunit.TraitAttribute("FeatureTitle", "Search for flights by route and date")]
        [Xunit.TraitAttribute("Description", "Search with missing departure airport code")]
        public void SearchWithMissingDepartureAirportCode()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Search with missing departure airport code", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 54
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 55
        testRunner.When("I search for flights from  to CDG on 2025-01-01", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 56
        testRunner.Then("an error message is returned which states that the departure airport code is requ" +
                        "ired", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Search with missing destination airport code")]
        [Xunit.TraitAttribute("FeatureTitle", "Search for flights by route and date")]
        [Xunit.TraitAttribute("Description", "Search with missing destination airport code")]
        public void SearchWithMissingDestinationAirportCode()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Search with missing destination airport code", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 58
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 59
        testRunner.When("I search for flights from YVR to  on 2025-01-01", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 60
        testRunner.Then("an error message is returned which states that the destination airport code is re" +
                        "quired", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Search with the same departure and destination airports")]
        [Xunit.TraitAttribute("FeatureTitle", "Search for flights by route and date")]
        [Xunit.TraitAttribute("Description", "Search with the same departure and destination airports")]
        public void SearchWithTheSameDepartureAndDestinationAirports()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Search with the same departure and destination airports", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 62
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 63
        testRunner.When("I search for flights from YVR to YVR on 2025-01-01", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 64
        testRunner.Then("an error message is returned which states that the departure and destination airp" +
                        "orts cannot be the same", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="All flights have already departed")]
        [Xunit.TraitAttribute("FeatureTitle", "Search for flights by route and date")]
        [Xunit.TraitAttribute("Description", "All flights have already departed")]
        public void AllFlightsHaveAlreadyDeparted()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("All flights have already departed", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 66
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                            "FlightNumber",
                            "DepartureAirportIataCode",
                            "DepartureAirportTimeZone",
                            "DestinationAirportIataCode",
                            "DestinationAirportTimeZone",
                            "DepartureTime",
                            "ArrivalTime",
                            "EconomyPrice",
                            "BusinessPrice",
                            "AvailableEconomySeats",
                            "AvailableBusinessSeats"});
                table9.AddRow(new string[] {
                            "EA123",
                            "YVR",
                            "America/Vancouver",
                            "CDG",
                            "Europe/Paris",
                            "2024-01-01T10:00:00",
                            "2024-01-02T05:00:00",
                            "1200.00",
                            "4500.00",
                            "50",
                            "10"});
#line 67
        testRunner.Given("the following flights exist:", ((string)(null)), table9, "Given ");
#line hidden
#line 70
        testRunner.When("I search for flights from YVR to CDG on 2025-01-03", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 71
        testRunner.Then("no flights are returned", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Search when some flights have already departed")]
        [Xunit.TraitAttribute("FeatureTitle", "Search for flights by route and date")]
        [Xunit.TraitAttribute("Description", "Search when some flights have already departed")]
        public void SearchWhenSomeFlightsHaveAlreadyDeparted()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Search when some flights have already departed", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 73
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                            "FlightNumber",
                            "DepartureAirportIataCode",
                            "DepartureAirportTimeZone",
                            "DestinationAirportIataCode",
                            "DestinationAirportTimeZone",
                            "DepartureTime",
                            "ArrivalTime",
                            "EconomyPrice",
                            "BusinessPrice",
                            "AvailableEconomySeats",
                            "AvailableBusinessSeats"});
                table10.AddRow(new string[] {
                            "EA123",
                            "YVR",
                            "America/Vancouver",
                            "CDG",
                            "Europe/Paris",
                            "2024-01-01T10:00:00",
                            "2024-01-02T05:00:00",
                            "1200.00",
                            "4500.00",
                            "50",
                            "10"});
                table10.AddRow(new string[] {
                            "EA124",
                            "YVR",
                            "America/Vancouver",
                            "CDG",
                            "Europe/Paris",
                            "2025-01-01T14:00:00",
                            "2025-01-02T09:00:00",
                            "1200.00",
                            "4500.00",
                            "50",
                            "10"});
#line 74
        testRunner.Given("the following flights exist:", ((string)(null)), table10, "Given ");
#line hidden
#line 78
        testRunner.When("I search for flights from YVR to CDG on 2025-01-01", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                            "FlightNumber",
                            "DepartureAirportIataCode",
                            "DepartureAirportTimeZone",
                            "DestinationAirportIataCode",
                            "DestinationAirportTimeZone",
                            "DepartureTime",
                            "ArrivalTime",
                            "EconomyPrice",
                            "BusinessPrice",
                            "AvailableEconomySeats",
                            "AvailableBusinessSeats"});
                table11.AddRow(new string[] {
                            "EA124",
                            "YVR",
                            "America/Vancouver",
                            "CDG",
                            "Europe/Paris",
                            "2025-01-01T14:00:00",
                            "2025-01-02T09:00:00",
                            "1200.00",
                            "4500.00",
                            "50",
                            "10"});
#line 79
        testRunner.Then("the following flights are returned:", ((string)(null)), table11, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Search with missing date")]
        [Xunit.TraitAttribute("FeatureTitle", "Search for flights by route and date")]
        [Xunit.TraitAttribute("Description", "Search with missing date")]
        public void SearchWithMissingDate()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Search with missing date", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 83
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 84
        testRunner.When("I search for flights from YVR to CDG on", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 85
        testRunner.Then("an error message is returned which states that the date parameter is required", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                SearchForFlightsByRouteAndDateFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                SearchForFlightsByRouteAndDateFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
