// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Flights.Api.AcceptanceTests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class SearchForFlightsByRouteAndDateFeature : object, Xunit.IClassFixture<SearchForFlightsByRouteAndDateFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "SearchForFlightsByRouteAndDate.feature"
#line hidden
        
        public SearchForFlightsByRouteAndDateFeature(SearchForFlightsByRouteAndDateFeature.FixtureData fixtureData, Flights_Api_AcceptanceTests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Search for flights by route and date", "  As a customer\r\n  I want to search for flights by route and date\r\n  So that I ca" +
                    "n evaluate the options available to me", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Search for flights by route and date")]
        [Xunit.TraitAttribute("FeatureTitle", "Search for flights by route and date")]
        [Xunit.TraitAttribute("Description", "Search for flights by route and date")]
        public void SearchForFlightsByRouteAndDate()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Search for flights by route and date", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 6
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                            "FlightNumber",
                            "DepartureAirport",
                            "ArrivalAirport",
                            "DepartureTime",
                            "ArrivalTime",
                            "Price"});
                table1.AddRow(new string[] {
                            "1",
                            "LHR",
                            "CDG",
                            "2020-01-01T10:00:00",
                            "2020-01-01T12:00:00",
                            "100.00"});
                table1.AddRow(new string[] {
                            "2",
                            "CDG",
                            "LHR",
                            "2020-01-01T14:00:00",
                            "2020-01-01T16:00:00",
                            "100.00"});
#line 7
    testRunner.Given("the following flights exist:", ((string)(null)), table1, "Given ");
#line hidden
#line 11
    testRunner.When("I search for flights from \"LHR\" to \"CDG\" on \"2020-01-01\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                            "FlightNumber",
                            "DepartureAirport",
                            "ArrivalAirport",
                            "DepartureTime",
                            "ArrivalTime",
                            "Price"});
                table2.AddRow(new string[] {
                            "1",
                            "LHR",
                            "CDG",
                            "2020-01-01T10:00:00",
                            "2020-01-01T12:00:00",
                            "100.00"});
#line 12
    testRunner.Then("the following flights should be returned:", ((string)(null)), table2, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                SearchForFlightsByRouteAndDateFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                SearchForFlightsByRouteAndDateFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
