// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Flights.Api.AcceptanceTests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class SearchForFlightsByRouteAndDateFeature : object, Xunit.IClassFixture<SearchForFlightsByRouteAndDateFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "SearchForFlightsByRouteAndDate.feature"
#line hidden
        
        public SearchForFlightsByRouteAndDateFeature(SearchForFlightsByRouteAndDateFeature.FixtureData fixtureData, Flights_Api_AcceptanceTests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Search for flights by route and date", "  As a customer\r\n  I want to search for flights by route and date\r\n  So that I ca" +
                    "n evaluate the options available to me", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Search for flights by route and date with valid results")]
        [Xunit.TraitAttribute("FeatureTitle", "Search for flights by route and date")]
        [Xunit.TraitAttribute("Description", "Search for flights by route and date with valid results")]
        public void SearchForFlightsByRouteAndDateWithValidResults()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Search for flights by route and date with valid results", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 6
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                            "FlightNumber",
                            "DepartureAirport",
                            "ArrivalAirport",
                            "DepartureTime",
                            "ArrivalTime",
                            "EconomyPrice",
                            "BusinessPrice",
                            "AvailableEconomySeats",
                            "AvailableBusinessSeats"});
                table1.AddRow(new string[] {
                            "EA123",
                            "YVR",
                            "CDG",
                            "2020-01-01T10:00:00",
                            "2020-01-02T05:00:00",
                            "1200.00",
                            "4500.00",
                            "50",
                            "10"});
                table1.AddRow(new string[] {
                            "EA124",
                            "YVR",
                            "CDG",
                            "2020-01-01T14:00:00",
                            "2020-01-02T09:00:00",
                            "1200.00",
                            "4500.00",
                            "50",
                            "10"});
                table1.AddRow(new string[] {
                            "EA125",
                            "YVR",
                            "LHR",
                            "2020-01-01T09:00:00",
                            "2020-01-02T04:00:00",
                            "1000.00",
                            "4000.00",
                            "60",
                            "15"});
#line 7
    testRunner.Given("the following flights exist:", ((string)(null)), table1, "Given ");
#line hidden
#line 12
    testRunner.When("I search for flights from YVR to CDG on 2020-01-01", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                            "FlightNumber",
                            "DepartureAirport",
                            "ArrivalAirport",
                            "DepartureTime",
                            "ArrivalTime",
                            "EconomyPrice",
                            "BusinessPrice",
                            "AvailableEconomySeats",
                            "AvailableBusinessSeats"});
                table2.AddRow(new string[] {
                            "EA123",
                            "YVR",
                            "CDG",
                            "2020-01-01T10:00:00",
                            "2020-01-02T05:00:00",
                            "1200.00",
                            "4500.00",
                            "50",
                            "10"});
                table2.AddRow(new string[] {
                            "EA124",
                            "YVR",
                            "CDG",
                            "2020-01-01T14:00:00",
                            "2020-01-02T09:00:00",
                            "1200.00",
                            "4500.00",
                            "50",
                            "10"});
#line 13
    testRunner.Then("the following flights are returned:", ((string)(null)), table2, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="No flights available for the given route and date")]
        [Xunit.TraitAttribute("FeatureTitle", "Search for flights by route and date")]
        [Xunit.TraitAttribute("Description", "No flights available for the given route and date")]
        public void NoFlightsAvailableForTheGivenRouteAndDate()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("No flights available for the given route and date", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 18
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                            "FlightNumber",
                            "DepartureAirport",
                            "ArrivalAirport",
                            "DepartureTime",
                            "ArrivalTime",
                            "EconomyPrice",
                            "BusinessPrice",
                            "AvailableEconomySeats",
                            "AvailableBusinessSeats"});
                table3.AddRow(new string[] {
                            "EA123",
                            "YVR",
                            "CDG",
                            "2020-01-02T10:00:00",
                            "2020-01-03T05:00:00",
                            "1200.00",
                            "4500.00",
                            "50",
                            "10"});
#line 19
    testRunner.Given("the following flights exist:", ((string)(null)), table3, "Given ");
#line hidden
#line 22
    testRunner.When("I search for flights from YVR to CDG on 2020-01-01", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 23
    testRunner.Then("no flights are returned", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Search for flights on a different date but same route")]
        [Xunit.TraitAttribute("FeatureTitle", "Search for flights by route and date")]
        [Xunit.TraitAttribute("Description", "Search for flights on a different date but same route")]
        public void SearchForFlightsOnADifferentDateButSameRoute()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Search for flights on a different date but same route", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 25
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                            "FlightNumber",
                            "DepartureAirport",
                            "ArrivalAirport",
                            "DepartureTime",
                            "ArrivalTime",
                            "EconomyPrice",
                            "BusinessPrice",
                            "AvailableEconomySeats",
                            "AvailableBusinessSeats"});
                table4.AddRow(new string[] {
                            "EA126",
                            "YVR",
                            "CDG",
                            "2020-01-02T10:00:00",
                            "2020-01-03T05:00:00",
                            "1300.00",
                            "4600.00",
                            "45",
                            "8"});
#line 26
    testRunner.Given("the following flights exist:", ((string)(null)), table4, "Given ");
#line hidden
#line 29
    testRunner.When("I search for flights from YVR to CDG on 2020-01-02", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                            "FlightNumber",
                            "DepartureAirport",
                            "ArrivalAirport",
                            "DepartureTime",
                            "ArrivalTime",
                            "EconomyPrice",
                            "BusinessPrice",
                            "AvailableEconomySeats",
                            "AvailableBusinessSeats"});
                table5.AddRow(new string[] {
                            "EA126",
                            "YVR",
                            "CDG",
                            "2020-01-02T10:00:00",
                            "2020-01-03T05:00:00",
                            "1300.00",
                            "4600.00",
                            "45",
                            "8"});
#line 30
    testRunner.Then("the following flights are returned:", ((string)(null)), table5, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Search for flights with no matching route")]
        [Xunit.TraitAttribute("FeatureTitle", "Search for flights by route and date")]
        [Xunit.TraitAttribute("Description", "Search for flights with no matching route")]
        public void SearchForFlightsWithNoMatchingRoute()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Search for flights with no matching route", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 34
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                            "FlightNumber",
                            "DepartureAirport",
                            "ArrivalAirport",
                            "DepartureTime",
                            "ArrivalTime",
                            "EconomyPrice",
                            "BusinessPrice",
                            "AvailableEconomySeats",
                            "AvailableBusinessSeats"});
                table6.AddRow(new string[] {
                            "EA123",
                            "YVR",
                            "LHR",
                            "2020-01-01T10:00:00",
                            "2020-01-02T05:00:00",
                            "1000.00",
                            "4000.00",
                            "60",
                            "15"});
#line 35
    testRunner.Given("the following flights exist:", ((string)(null)), table6, "Given ");
#line hidden
#line 38
    testRunner.When("I search for flights from YVR to CDG on 2020-01-01", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 39
    testRunner.Then("no flights are returned", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                SearchForFlightsByRouteAndDateFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                SearchForFlightsByRouteAndDateFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
