// <auto-generated />
using System;
using Fleet.Api.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fleet.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240405162558_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fleet.Api.Entities.Aircraft", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AircraftStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("BasicEmptyWeight")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte>("EngineCount")
                        .HasColumnType("smallint");

                    b.Property<string>("EngineModel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<float>("FlightHours")
                        .HasColumnType("real");

                    b.Property<int>("FuelCapacity")
                        .HasColumnType("integer");

                    b.Property<int>("FuelOnboard")
                        .HasColumnType("integer");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)");

                    b.Property<int>("MaximumCargoWeight")
                        .HasColumnType("integer");

                    b.Property<int>("MaximumLandingWeight")
                        .HasColumnType("integer");

                    b.Property<int>("MaximumTakeoffWeight")
                        .HasColumnType("integer");

                    b.Property<int>("MaximumZeroFuelWeight")
                        .HasColumnType("integer");

                    b.Property<byte>("MinimumCabinCrew")
                        .HasColumnType("smallint");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("OperationalStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("ProductionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Registration")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.Property<string>("SeatingConfiguration")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<int>("ServiceCeiling")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TypeDesignator")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("Wingspan")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("Aircraft");
                });
#pragma warning restore 612, 618
        }
    }
}
