// <auto-generated />
using System;
using System.Collections.Generic;
using Flights.Api.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Flights.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241008011811_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Flights.Api.Entities.Flight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("flight_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.ComplexProperty<Dictionary<string, object>>("AvailableSeats", "Flights.Api.Entities.Flight.AvailableSeats#AvailableSeats", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Business")
                                .HasColumnType("integer")
                                .HasColumnName("available_seats_business");

                            b1.Property<int>("Economy")
                                .HasColumnType("integer")
                                .HasColumnName("available_seats_economy");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Pricing", "Flights.Api.Entities.Flight.Pricing#FlightPricing", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("BusinessPrice")
                                .HasColumnType("numeric")
                                .HasColumnName("pricing_business_price");

                            b1.Property<decimal>("EconomyPrice")
                                .HasColumnType("numeric")
                                .HasColumnName("pricing_economy_price");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Schedule", "Flights.Api.Entities.Flight.Schedule#FlightSchedule", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTime>("ArrivalTime")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("schedule_arrival_time");

                            b1.Property<string>("Departure")
                                .IsRequired()
                                .HasMaxLength(10)
                                .IsUnicode(false)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("schedule_departure")
                                .HasAnnotation("Npgsql:CheckConstraint", "Departure = upper(Departure)");

                            b1.Property<DateTime>("DepartureTime")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("schedule_departure_time");

                            b1.Property<string>("Destination")
                                .IsRequired()
                                .HasMaxLength(10)
                                .IsUnicode(false)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("schedule_destination")
                                .HasAnnotation("Npgsql:CheckConstraint", "Destination = upper(Destination)");
                        });

                    b.HasKey("Id")
                        .HasName("pk_flights");

                    b.ToTable("flights", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
