// <auto-generated />
using System;
using System.Collections.Generic;
using Flights.Api.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Flights.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250122021130_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Flights.Api.Domain.Bookings.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("PassengerEmail")
                        .HasColumnType("text")
                        .HasColumnName("passenger_email");

                    b.Property<string>("PassengerName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("passenger_name");

                    b.Property<Guid>("SeatId")
                        .HasColumnType("uuid")
                        .HasColumnName("seat_id");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_bookings");

                    b.HasIndex("SeatId")
                        .HasDatabaseName("ix_bookings_seat_id");

                    b.ToTable("bookings", (string)null);
                });

            modelBuilder.Entity("Flights.Api.Domain.Flights.Flight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("flight_number");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.ComplexProperty<Dictionary<string, object>>("Schedule", "Flights.Api.Domain.Flights.Flight.Schedule#FlightSchedule", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<ZonedDateTime>("ArrivalTime")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("schedule_arrival_time");

                            b1.Property<ZonedDateTime>("DepartureTime")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("schedule_departure_time");

                            b1.ComplexProperty<Dictionary<string, object>>("DepartureAirport", "Flights.Api.Domain.Flights.Flight.Schedule#FlightSchedule.DepartureAirport#Airport", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("IataCode")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .IsUnicode(false)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("schedule_departure_airport_iata_code")
                                        .HasAnnotation("Npgsql:CheckConstraint", "Departure = upper(Departure)");

                                    b2.Property<string>("TimeZone")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .IsUnicode(false)
                                        .HasColumnType("character varying(50)")
                                        .HasColumnName("schedule_departure_airport_time_zone");
                                });

                            b1.ComplexProperty<Dictionary<string, object>>("DestinationAirport", "Flights.Api.Domain.Flights.Flight.Schedule#FlightSchedule.DestinationAirport#Airport", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("IataCode")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .IsUnicode(false)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("schedule_destination_airport_iata_code")
                                        .HasAnnotation("Npgsql:CheckConstraint", "Destination = upper(Destination)");

                                    b2.Property<string>("TimeZone")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .IsUnicode(false)
                                        .HasColumnType("character varying(50)")
                                        .HasColumnName("schedule_destination_airport_time_zone");
                                });
                        });

                    b.HasKey("Id")
                        .HasName("pk_flights");

                    b.ToTable("flights", (string)null);
                });

            modelBuilder.Entity("Flights.Api.Domain.Seats.Seat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FlightId")
                        .HasColumnType("uuid")
                        .HasColumnName("flight_id");

                    b.Property<bool>("IsBooked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_booked");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("seat_number");

                    b.Property<string>("SeatType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("seat_type");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_seats");

                    b.HasIndex("FlightId")
                        .HasDatabaseName("ix_seats_flight_id");

                    b.ToTable("seats", (string)null);
                });

            modelBuilder.Entity("Flights.Api.Domain.Bookings.Booking", b =>
                {
                    b.HasOne("Flights.Api.Domain.Seats.Seat", "Seat")
                        .WithMany()
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_seats_seat_id");

                    b.Navigation("Seat");
                });

            modelBuilder.Entity("Flights.Api.Domain.Seats.Seat", b =>
                {
                    b.HasOne("Flights.Api.Domain.Flights.Flight", null)
                        .WithMany("Seats")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_seats_flights_flight_id");
                });

            modelBuilder.Entity("Flights.Api.Domain.Flights.Flight", b =>
                {
                    b.Navigation("Seats");
                });
#pragma warning restore 612, 618
        }
    }
}
