name: CI-CD Pipe

on:
    push:
        branches:
            - "main"

env:
    DOTNET_VERSION: "9.0.x"

jobs:
    Terraform:
        name: Terraform Check
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout
              uses: actions/checkout@v5
            - name: Terraform Check
              run: terraform fmt -check=true -recursive

    Prettier:
        name: Prettier Check
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v5
            - name: Prettier Check
              run: npx prettier --check .

    DotNet:
        name: DotNet Build and Test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v5
            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: ${{ env.DOTNET_VERSION }}
            - name: DotNet Format
              run: dotnet format --verify-no-changes
            - name: DotNet Build
              run: dotnet build --configuration Release --no-restore
            - name: DotNet Test
              run: dotnet test -v d --configuration Release --no-restore --no-build

    Deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v5
            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: eu-west-2
            - name: Terraform Init (with module git auth)
              working-directory: terraform
              env:
                  TF_MODULE_KEY: ${{ secrets.TF_MODULE_KEY }}
              run: |
                  # Configure git to use TF_MODULE_KEY only during init to fetch private modules
                  git config --global url."https://${TF_MODULE_KEY}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
                  terraform init -input=false
                  # Remove temporary git config so subsequent steps fall back to default token
                  git config --global --unset-all url."https://${TF_MODULE_KEY}:x-oauth-basic@github.com/".insteadOf || true
            - name: Terraform Apply
              working-directory: terraform
              run: terraform apply -auto-approve -input=false
