name: Preflight Checks

on:
  push:
    branches:
      - master

env:
  DOTNET_VERSION: "8.0.x"
  PYTHON_VERSION: "3.x"
  URLS: ${{ secrets.URLS }}
  LOGDRIVER: ${{ secrets.LOGDRIVER }}

jobs:
  DotNet:
    name: DotNet Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: DotNet Restore
        run: dotnet restore
      - name: DotNet Build
        run: dotnet build --configuration Release --no-restore
      - name: DotNet Test
        run: dotnet test --configuration Release --no-restore --no-build

  CodeFormatCheck:
    name: Code Format Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Fail on Long Lines
        run: |
          output=$(python3 .github/scripts/longlines.py)
          if [ ! -z "$output" ]; then
            echo "$output"
            exit 1
          fi
      - name: Fail on Long Methods
        run: |
          output=$(python3 .github/scripts/longmethods.py)
          if [ ! -z "$output" ]; then
            echo "$output"
            exit 1
          fi

  Docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Set up Docker Environment
        run: |
          echo "URLS=${{ secrets.URLS }}" >> $GITHUB_ENV
          echo "LOGDRIVER=${{ secrets.LOGDRIVER }}" >> $GITHUB_ENV
      - name: Docker Compose Up
        run: docker-compose up -d

  Trivy:
    needs: Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Container Scan
        run: |
          . .github/scripts/trivy.sh

  Semgrep:
    name: Semgrep Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install Semgrep
        run: pip install semgrep
      - name: Run Semgrep
        run: semgrep --config=p/r2c --error
